server:
  port: 7771
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods :
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowedCredentials: true #是否允许携带cookie
            maxAge: 360000

      routes:
        - id: go-cus #路由标识，必须唯一
          uri: lb://cus-service #路由的目标地址,lb开头代表使用负载均衡策略
          predicates:
            - Path=/cus/** #路由断言，判断路径是否以/cus开头，如果是就符合转发
          filters:
            # 使用内置的HystrixGatewayFilterFactory工厂类做熔断降级
            - name: HystrixCus
              args:
                # Hystrix的bean名称
                name: appHystrixCus
                # Hystrix超时降级后调用uri地址
                fallbackUri: 'forward:/gatewayFallbackCus'
        - id: go-modules
          uri: lb://modules-service
          predicates:
            - Path=/mod/**
          filters:
            - name: HystrixMod
              args:
                name: appHystrixMod
                 # Hystrix超时降级后调用uri地址
                fallbackUri: 'forward:/gatewayFallbackMod'
      # hystrix设置隔离策略为信号量，超时时间为 2 秒
      hystrix:
        command:
          default:
            execution:
              isolation:
                strategy: SEMAPHORE
              thread:
                timeoutInMilliseconds: 2000
      discovery:
        locator:
          enabled: true
    nacos:
      server-addr: localhost:8848

